name: "Export Nix closure"
description: "Export a Nix closure to the cache"
runs:
  using: "composite"
  steps:
    - uses: vapourismo/workflows/copy-nix-store@master
      with:
        target: ssh://nix-ssh@nix.cache.hwlium.com
