name: "Setup Nix"
description: "Setup Nix with persistent caching"
inputs:
  ssh-private-key:
    description: "SSH private key with which to access the Nix cache server"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes
