name: Main

on:
  push:
    branches:
      - master
      - feature/*

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

jobs:
  examples-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v17

      - run: nix-build -v examples/standard/default.nix

  examples-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf: |
            extra-experimental-features = nix-command flakes

      - run: |
          nix -vL build --impure ./examples/flake --override-input opam-nix-integration path:./.
