name: Main

on:
  push:
    branches:
      - master
      - feature/*

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 8 * * *"

jobs:
  examples-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.NIX_CACHE_SSH_KEY }}

      - run: nix-build -v examples/standard/default.nix

      - if: always()
        uses: ./.github/actions/export-nix-store

  examples-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./.github/actions/setup-nix
        with:
          ssh-private-key: ${{ secrets.NIX_CACHE_SSH_KEY }}

      - run: |
          nix -vL build --impure ./examples/flake --override-input opam-nix-integration path:./.

      - if: always()
        uses: ./.github/actions/export-nix-store
